version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=mente_sa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword 
    ports:
      - 5432:5432
    volumes:
      - postgres_mente_sa:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: .
    command: npm run dev
    ports:
      - 3333:3333
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_mente_sa:
    external: true
  mongo_mente_sa:
    external: true
